//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ForLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class ForLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FOR=1, TO=2, PRINTLN=3, ARROW=4, LPAREN=5, RPAREN=6, LBRACE=7, RBRACE=8, 
		SEMICOLON=9, UNDERSCORE=10, IDENTIFIER=11, DIGIT=12, NEWLINE=13, WS=14;
	public const int
		RULE_start = 0, RULE_keywordFor = 1, RULE_openBracketCycle = 2, RULE_idCycle = 3, 
		RULE_operatorExpression = 4, RULE_beginNumber = 5, RULE_operatorTo = 6, 
		RULE_endNumber = 7, RULE_openCurly = 8, RULE_operatorNewline = 9, RULE_cycleBody = 10, 
		RULE_keywordPrintln = 11, RULE_openBracePrintln = 12, RULE_idCycleBody = 13, 
		RULE_closeBracePrintln = 14, RULE_closeCurly = 15;
	public static readonly string[] ruleNames = {
		"start", "keywordFor", "openBracketCycle", "idCycle", "operatorExpression", 
		"beginNumber", "operatorTo", "endNumber", "openCurly", "operatorNewline", 
		"cycleBody", "keywordPrintln", "openBracePrintln", "idCycleBody", "closeBracePrintln", 
		"closeCurly"
	};

	private static readonly string[] _LiteralNames = {
		null, "'for'", "'to'", "'println'", "'<-'", "'('", "')'", "'{'", "'}'", 
		"';'", "'_'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FOR", "TO", "PRINTLN", "ARROW", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"SEMICOLON", "UNDERSCORE", "IDENTIFIER", "DIGIT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ForLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ForLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ForLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ForLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(ForLangParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public KeywordForContext keywordFor() {
			return GetRuleContext<KeywordForContext>(0);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			Match(FOR);
			State = 33;
			keywordFor();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KeywordForContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(ForLangParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OpenBracketCycleContext openBracketCycle() {
			return GetRuleContext<OpenBracketCycleContext>(0);
		}
		public KeywordForContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_keywordFor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterKeywordFor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitKeywordFor(this);
		}
	}

	[RuleVersion(0)]
	public KeywordForContext keywordFor() {
		KeywordForContext _localctx = new KeywordForContext(Context, State);
		EnterRule(_localctx, 2, RULE_keywordFor);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			Match(LPAREN);
			State = 36;
			openBracketCycle();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpenBracketCycleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ForLangParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdCycleContext idCycle() {
			return GetRuleContext<IdCycleContext>(0);
		}
		public OpenBracketCycleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_openBracketCycle; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOpenBracketCycle(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOpenBracketCycle(this);
		}
	}

	[RuleVersion(0)]
	public OpenBracketCycleContext openBracketCycle() {
		OpenBracketCycleContext _localctx = new OpenBracketCycleContext(Context, State);
		EnterRule(_localctx, 4, RULE_openBracketCycle);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			Match(IDENTIFIER);
			State = 39;
			idCycle();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdCycleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(ForLangParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperatorExpressionContext operatorExpression() {
			return GetRuleContext<OperatorExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(ForLangParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(ForLangParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIGIT() { return GetTokens(ForLangParser.DIGIT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT(int i) {
			return GetToken(ForLangParser.DIGIT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] UNDERSCORE() { return GetTokens(ForLangParser.UNDERSCORE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNDERSCORE(int i) {
			return GetToken(ForLangParser.UNDERSCORE, i);
		}
		public IdCycleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idCycle; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterIdCycle(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitIdCycle(this);
		}
	}

	[RuleVersion(0)]
	public IdCycleContext idCycle() {
		IdCycleContext _localctx = new IdCycleContext(Context, State);
		EnterRule(_localctx, 6, RULE_idCycle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) {
				{
				{
				State = 41;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 47;
			Match(ARROW);
			State = 48;
			operatorExpression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT() { return GetToken(ForLangParser.DIGIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BeginNumberContext beginNumber() {
			return GetRuleContext<BeginNumberContext>(0);
		}
		public OperatorExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operatorExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOperatorExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOperatorExpression(this);
		}
	}

	[RuleVersion(0)]
	public OperatorExpressionContext operatorExpression() {
		OperatorExpressionContext _localctx = new OperatorExpressionContext(Context, State);
		EnterRule(_localctx, 8, RULE_operatorExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			Match(DIGIT);
			State = 51;
			beginNumber();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BeginNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT() { return GetToken(ForLangParser.DIGIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BeginNumberContext beginNumber() {
			return GetRuleContext<BeginNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TO() { return GetToken(ForLangParser.TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperatorToContext operatorTo() {
			return GetRuleContext<OperatorToContext>(0);
		}
		public BeginNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_beginNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterBeginNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitBeginNumber(this);
		}
	}

	[RuleVersion(0)]
	public BeginNumberContext beginNumber() {
		BeginNumberContext _localctx = new BeginNumberContext(Context, State);
		EnterRule(_localctx, 10, RULE_beginNumber);
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DIGIT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 53;
				Match(DIGIT);
				State = 54;
				beginNumber();
				}
				break;
			case TO:
				EnterOuterAlt(_localctx, 2);
				{
				State = 55;
				Match(TO);
				State = 56;
				operatorTo();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorToContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT() { return GetToken(ForLangParser.DIGIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EndNumberContext endNumber() {
			return GetRuleContext<EndNumberContext>(0);
		}
		public OperatorToContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operatorTo; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOperatorTo(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOperatorTo(this);
		}
	}

	[RuleVersion(0)]
	public OperatorToContext operatorTo() {
		OperatorToContext _localctx = new OperatorToContext(Context, State);
		EnterRule(_localctx, 12, RULE_operatorTo);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			Match(DIGIT);
			State = 60;
			endNumber();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT() { return GetToken(ForLangParser.DIGIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EndNumberContext endNumber() {
			return GetRuleContext<EndNumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(ForLangParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OpenCurlyContext openCurly() {
			return GetRuleContext<OpenCurlyContext>(0);
		}
		public EndNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterEndNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitEndNumber(this);
		}
	}

	[RuleVersion(0)]
	public EndNumberContext endNumber() {
		EndNumberContext _localctx = new EndNumberContext(Context, State);
		EnterRule(_localctx, 14, RULE_endNumber);
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DIGIT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 62;
				Match(DIGIT);
				State = 63;
				endNumber();
				}
				break;
			case RPAREN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				Match(RPAREN);
				State = 65;
				openCurly();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpenCurlyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(ForLangParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(ForLangParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperatorNewlineContext operatorNewline() {
			return GetRuleContext<OperatorNewlineContext>(0);
		}
		public OpenCurlyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_openCurly; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOpenCurly(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOpenCurly(this);
		}
	}

	[RuleVersion(0)]
	public OpenCurlyContext openCurly() {
		OpenCurlyContext _localctx = new OpenCurlyContext(Context, State);
		EnterRule(_localctx, 16, RULE_openCurly);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			Match(LBRACE);
			State = 69;
			Match(NEWLINE);
			State = 70;
			operatorNewline();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorNewlineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRINTLN() { return GetToken(ForLangParser.PRINTLN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CycleBodyContext cycleBody() {
			return GetRuleContext<CycleBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(ForLangParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CloseCurlyContext closeCurly() {
			return GetRuleContext<CloseCurlyContext>(0);
		}
		public OperatorNewlineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operatorNewline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOperatorNewline(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOperatorNewline(this);
		}
	}

	[RuleVersion(0)]
	public OperatorNewlineContext operatorNewline() {
		OperatorNewlineContext _localctx = new OperatorNewlineContext(Context, State);
		EnterRule(_localctx, 18, RULE_operatorNewline);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PRINTLN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72;
				Match(PRINTLN);
				State = 73;
				cycleBody();
				}
				break;
			case RBRACE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 74;
				Match(RBRACE);
				State = 75;
				closeCurly();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CycleBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public KeywordPrintlnContext keywordPrintln() {
			return GetRuleContext<KeywordPrintlnContext>(0);
		}
		public CycleBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cycleBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterCycleBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitCycleBody(this);
		}
	}

	[RuleVersion(0)]
	public CycleBodyContext cycleBody() {
		CycleBodyContext _localctx = new CycleBodyContext(Context, State);
		EnterRule(_localctx, 20, RULE_cycleBody);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			keywordPrintln();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KeywordPrintlnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(ForLangParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OpenBracePrintlnContext openBracePrintln() {
			return GetRuleContext<OpenBracePrintlnContext>(0);
		}
		public KeywordPrintlnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_keywordPrintln; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterKeywordPrintln(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitKeywordPrintln(this);
		}
	}

	[RuleVersion(0)]
	public KeywordPrintlnContext keywordPrintln() {
		KeywordPrintlnContext _localctx = new KeywordPrintlnContext(Context, State);
		EnterRule(_localctx, 22, RULE_keywordPrintln);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			Match(LPAREN);
			State = 81;
			openBracePrintln();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpenBracePrintlnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ForLangParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdCycleBodyContext idCycleBody() {
			return GetRuleContext<IdCycleBodyContext>(0);
		}
		public OpenBracePrintlnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_openBracePrintln; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterOpenBracePrintln(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitOpenBracePrintln(this);
		}
	}

	[RuleVersion(0)]
	public OpenBracePrintlnContext openBracePrintln() {
		OpenBracePrintlnContext _localctx = new OpenBracePrintlnContext(Context, State);
		EnterRule(_localctx, 24, RULE_openBracePrintln);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			Match(IDENTIFIER);
			State = 84;
			idCycleBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdCycleBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(ForLangParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CloseBracePrintlnContext closeBracePrintln() {
			return GetRuleContext<CloseBracePrintlnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(ForLangParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(ForLangParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIGIT() { return GetTokens(ForLangParser.DIGIT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT(int i) {
			return GetToken(ForLangParser.DIGIT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] UNDERSCORE() { return GetTokens(ForLangParser.UNDERSCORE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNDERSCORE(int i) {
			return GetToken(ForLangParser.UNDERSCORE, i);
		}
		public IdCycleBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idCycleBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterIdCycleBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitIdCycleBody(this);
		}
	}

	[RuleVersion(0)]
	public IdCycleBodyContext idCycleBody() {
		IdCycleBodyContext _localctx = new IdCycleBodyContext(Context, State);
		EnterRule(_localctx, 26, RULE_idCycleBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) {
				{
				{
				State = 86;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 92;
			Match(RPAREN);
			State = 93;
			closeBracePrintln();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CloseBracePrintlnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(ForLangParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperatorNewlineContext operatorNewline() {
			return GetRuleContext<OperatorNewlineContext>(0);
		}
		public CloseBracePrintlnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_closeBracePrintln; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterCloseBracePrintln(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitCloseBracePrintln(this);
		}
	}

	[RuleVersion(0)]
	public CloseBracePrintlnContext closeBracePrintln() {
		CloseBracePrintlnContext _localctx = new CloseBracePrintlnContext(Context, State);
		EnterRule(_localctx, 28, RULE_closeBracePrintln);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			Match(NEWLINE);
			State = 96;
			operatorNewline();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CloseCurlyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(ForLangParser.SEMICOLON, 0); }
		public CloseCurlyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_closeCurly; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.EnterCloseCurly(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IForLangListener typedListener = listener as IForLangListener;
			if (typedListener != null) typedListener.ExitCloseCurly(this);
		}
	}

	[RuleVersion(0)]
	public CloseCurlyContext closeCurly() {
		CloseCurlyContext _localctx = new CloseCurlyContext(Context, State);
		EnterRule(_localctx, 30, RULE_closeCurly);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,14,101,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,1,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,3,5,3,43,8,3,10,3,12,3,
		46,9,3,1,3,1,3,1,3,1,4,1,4,1,4,1,5,1,5,1,5,1,5,3,5,58,8,5,1,6,1,6,1,6,
		1,7,1,7,1,7,1,7,3,7,67,8,7,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,3,9,77,8,9,
		1,10,1,10,1,11,1,11,1,11,1,12,1,12,1,12,1,13,5,13,88,8,13,10,13,12,13,
		91,9,13,1,13,1,13,1,13,1,14,1,14,1,14,1,15,1,15,1,15,0,0,16,0,2,4,6,8,
		10,12,14,16,18,20,22,24,26,28,30,0,1,1,0,10,12,89,0,32,1,0,0,0,2,35,1,
		0,0,0,4,38,1,0,0,0,6,44,1,0,0,0,8,50,1,0,0,0,10,57,1,0,0,0,12,59,1,0,0,
		0,14,66,1,0,0,0,16,68,1,0,0,0,18,76,1,0,0,0,20,78,1,0,0,0,22,80,1,0,0,
		0,24,83,1,0,0,0,26,89,1,0,0,0,28,95,1,0,0,0,30,98,1,0,0,0,32,33,5,1,0,
		0,33,34,3,2,1,0,34,1,1,0,0,0,35,36,5,5,0,0,36,37,3,4,2,0,37,3,1,0,0,0,
		38,39,5,11,0,0,39,40,3,6,3,0,40,5,1,0,0,0,41,43,7,0,0,0,42,41,1,0,0,0,
		43,46,1,0,0,0,44,42,1,0,0,0,44,45,1,0,0,0,45,47,1,0,0,0,46,44,1,0,0,0,
		47,48,5,4,0,0,48,49,3,8,4,0,49,7,1,0,0,0,50,51,5,12,0,0,51,52,3,10,5,0,
		52,9,1,0,0,0,53,54,5,12,0,0,54,58,3,10,5,0,55,56,5,2,0,0,56,58,3,12,6,
		0,57,53,1,0,0,0,57,55,1,0,0,0,58,11,1,0,0,0,59,60,5,12,0,0,60,61,3,14,
		7,0,61,13,1,0,0,0,62,63,5,12,0,0,63,67,3,14,7,0,64,65,5,6,0,0,65,67,3,
		16,8,0,66,62,1,0,0,0,66,64,1,0,0,0,67,15,1,0,0,0,68,69,5,7,0,0,69,70,5,
		13,0,0,70,71,3,18,9,0,71,17,1,0,0,0,72,73,5,3,0,0,73,77,3,20,10,0,74,75,
		5,8,0,0,75,77,3,30,15,0,76,72,1,0,0,0,76,74,1,0,0,0,77,19,1,0,0,0,78,79,
		3,22,11,0,79,21,1,0,0,0,80,81,5,5,0,0,81,82,3,24,12,0,82,23,1,0,0,0,83,
		84,5,11,0,0,84,85,3,26,13,0,85,25,1,0,0,0,86,88,7,0,0,0,87,86,1,0,0,0,
		88,91,1,0,0,0,89,87,1,0,0,0,89,90,1,0,0,0,90,92,1,0,0,0,91,89,1,0,0,0,
		92,93,5,6,0,0,93,94,3,28,14,0,94,27,1,0,0,0,95,96,5,13,0,0,96,97,3,18,
		9,0,97,29,1,0,0,0,98,99,5,9,0,0,99,31,1,0,0,0,5,44,57,66,76,89
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
