//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ForLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class ForLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FOR=1, TO=2, PRINTLN=3, ARROW=4, LPAREN=5, RPAREN=6, LBRACE=7, RBRACE=8, 
		SEMICOLON=9, UNDERSCORE=10, IDENTIFIER=11, DIGIT=12, NEWLINE=13, WS=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"FOR", "TO", "PRINTLN", "ARROW", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"SEMICOLON", "UNDERSCORE", "IDENTIFIER", "DIGIT", "NEWLINE", "WS"
	};


	public ForLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ForLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'for'", "'to'", "'println'", "'<-'", "'('", "')'", "'{'", "'}'", 
		"';'", "'_'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FOR", "TO", "PRINTLN", "ARROW", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"SEMICOLON", "UNDERSCORE", "IDENTIFIER", "DIGIT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ForLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ForLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,14,80,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,1,0,1,
		0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,4,
		1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,9,1,9,1,10,1,10,5,10,62,8,10,10,
		10,12,10,65,9,10,1,11,1,11,1,12,3,12,70,8,12,1,12,1,12,1,13,4,13,75,8,
		13,11,13,12,13,76,1,13,1,13,0,0,14,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,
		17,9,19,10,21,11,23,12,25,13,27,14,1,0,4,3,0,65,90,95,95,97,122,4,0,48,
		57,65,90,95,95,97,122,1,0,48,57,2,0,9,9,32,32,82,0,1,1,0,0,0,0,3,1,0,0,
		0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,
		0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,
		0,27,1,0,0,0,1,29,1,0,0,0,3,33,1,0,0,0,5,36,1,0,0,0,7,44,1,0,0,0,9,47,
		1,0,0,0,11,49,1,0,0,0,13,51,1,0,0,0,15,53,1,0,0,0,17,55,1,0,0,0,19,57,
		1,0,0,0,21,59,1,0,0,0,23,66,1,0,0,0,25,69,1,0,0,0,27,74,1,0,0,0,29,30,
		5,102,0,0,30,31,5,111,0,0,31,32,5,114,0,0,32,2,1,0,0,0,33,34,5,116,0,0,
		34,35,5,111,0,0,35,4,1,0,0,0,36,37,5,112,0,0,37,38,5,114,0,0,38,39,5,105,
		0,0,39,40,5,110,0,0,40,41,5,116,0,0,41,42,5,108,0,0,42,43,5,110,0,0,43,
		6,1,0,0,0,44,45,5,60,0,0,45,46,5,45,0,0,46,8,1,0,0,0,47,48,5,40,0,0,48,
		10,1,0,0,0,49,50,5,41,0,0,50,12,1,0,0,0,51,52,5,123,0,0,52,14,1,0,0,0,
		53,54,5,125,0,0,54,16,1,0,0,0,55,56,5,59,0,0,56,18,1,0,0,0,57,58,5,95,
		0,0,58,20,1,0,0,0,59,63,7,0,0,0,60,62,7,1,0,0,61,60,1,0,0,0,62,65,1,0,
		0,0,63,61,1,0,0,0,63,64,1,0,0,0,64,22,1,0,0,0,65,63,1,0,0,0,66,67,7,2,
		0,0,67,24,1,0,0,0,68,70,5,13,0,0,69,68,1,0,0,0,69,70,1,0,0,0,70,71,1,0,
		0,0,71,72,5,10,0,0,72,26,1,0,0,0,73,75,7,3,0,0,74,73,1,0,0,0,75,76,1,0,
		0,0,76,74,1,0,0,0,76,77,1,0,0,0,77,78,1,0,0,0,78,79,6,13,0,0,79,28,1,0,
		0,0,4,0,63,69,76,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
