//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ForLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ForLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IForLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] ForLangParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] ForLangParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.keywordFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordFor([NotNull] ForLangParser.KeywordForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.keywordFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordFor([NotNull] ForLangParser.KeywordForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openBracketCycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenBracketCycle([NotNull] ForLangParser.OpenBracketCycleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openBracketCycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenBracketCycle([NotNull] ForLangParser.OpenBracketCycleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.idCycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdCycle([NotNull] ForLangParser.IdCycleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.idCycle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdCycle([NotNull] ForLangParser.IdCycleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorExpression([NotNull] ForLangParser.OperatorExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorExpression([NotNull] ForLangParser.OperatorExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.beginNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeginNumber([NotNull] ForLangParser.BeginNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.beginNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeginNumber([NotNull] ForLangParser.BeginNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorTo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorTo([NotNull] ForLangParser.OperatorToContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorTo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorTo([NotNull] ForLangParser.OperatorToContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.endNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndNumber([NotNull] ForLangParser.EndNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.endNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndNumber([NotNull] ForLangParser.EndNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openCurly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenCurly([NotNull] ForLangParser.OpenCurlyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openCurly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenCurly([NotNull] ForLangParser.OpenCurlyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorNewline([NotNull] ForLangParser.OperatorNewlineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorNewline([NotNull] ForLangParser.OperatorNewlineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.cycleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCycleBody([NotNull] ForLangParser.CycleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.cycleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCycleBody([NotNull] ForLangParser.CycleBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.keywordPrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordPrintln([NotNull] ForLangParser.KeywordPrintlnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.keywordPrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordPrintln([NotNull] ForLangParser.KeywordPrintlnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openBracePrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenBracePrintln([NotNull] ForLangParser.OpenBracePrintlnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openBracePrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenBracePrintln([NotNull] ForLangParser.OpenBracePrintlnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.idCycleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdCycleBody([NotNull] ForLangParser.IdCycleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.idCycleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdCycleBody([NotNull] ForLangParser.IdCycleBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.closeBracePrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseBracePrintln([NotNull] ForLangParser.CloseBracePrintlnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.closeBracePrintln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseBracePrintln([NotNull] ForLangParser.CloseBracePrintlnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.closeCurly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseCurly([NotNull] ForLangParser.CloseCurlyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.closeCurly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseCurly([NotNull] ForLangParser.CloseCurlyContext context);
}
