//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ForLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IForLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ForLangBaseListener : IForLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] ForLangParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] ForLangParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.keywordFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywordFor([NotNull] ForLangParser.KeywordForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.keywordFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywordFor([NotNull] ForLangParser.KeywordForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openBracketCycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpenBracketCycle([NotNull] ForLangParser.OpenBracketCycleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openBracketCycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpenBracketCycle([NotNull] ForLangParser.OpenBracketCycleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.idCycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdCycle([NotNull] ForLangParser.IdCycleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.idCycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdCycle([NotNull] ForLangParser.IdCycleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorExpression([NotNull] ForLangParser.OperatorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorExpression([NotNull] ForLangParser.OperatorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.beginNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeginNumber([NotNull] ForLangParser.BeginNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.beginNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeginNumber([NotNull] ForLangParser.BeginNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorTo([NotNull] ForLangParser.OperatorToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorTo([NotNull] ForLangParser.OperatorToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.endNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndNumber([NotNull] ForLangParser.EndNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.endNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndNumber([NotNull] ForLangParser.EndNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openCurly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpenCurly([NotNull] ForLangParser.OpenCurlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openCurly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpenCurly([NotNull] ForLangParser.OpenCurlyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.operatorNewline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorNewline([NotNull] ForLangParser.OperatorNewlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.operatorNewline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorNewline([NotNull] ForLangParser.OperatorNewlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.cycleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycleBody([NotNull] ForLangParser.CycleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.cycleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycleBody([NotNull] ForLangParser.CycleBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.keywordPrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywordPrintln([NotNull] ForLangParser.KeywordPrintlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.keywordPrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywordPrintln([NotNull] ForLangParser.KeywordPrintlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.openBracePrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpenBracePrintln([NotNull] ForLangParser.OpenBracePrintlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.openBracePrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpenBracePrintln([NotNull] ForLangParser.OpenBracePrintlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.idCycleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdCycleBody([NotNull] ForLangParser.IdCycleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.idCycleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdCycleBody([NotNull] ForLangParser.IdCycleBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.closeBracePrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCloseBracePrintln([NotNull] ForLangParser.CloseBracePrintlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.closeBracePrintln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCloseBracePrintln([NotNull] ForLangParser.CloseBracePrintlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ForLangParser.closeCurly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCloseCurly([NotNull] ForLangParser.CloseCurlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ForLangParser.closeCurly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCloseCurly([NotNull] ForLangParser.CloseCurlyContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
